### ISSUE TITLE
program crashes

### ISSUE THREAD

**Issue by lordyoyo** [d0sboots/dyson-sphere-program#3] opened 2022-08-18 23:38 UTC
Hi! I'm trying to use your code to generate data from the gamefiles that can be parsed and used in a production tracker spreadsheet. Your program currently gives me this:

```  File "<dynamic TechProtoSet code>", line 17, in __init__
  File "<dynamic TechProtoSet code>", line 17, in <listcomp>
  File "<dynamic TechProto code>", line 31, in __init__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 16: invalid continuation byte

[process exited with code 1]

**Comment by d0sboots** [comment] 2022-08-21 03:34
Sorry for the slow response, it's been busy.

There's a decent chance that the underlying data has added a field somewhere, and that needs to be accounted for in the script. I'll take a look.

**Comment by d0sboots** [comment] 2022-08-26 01:49
I was able to reproduce the issue, with the exact same error message. The cause was new fields added to TechProto. I pushed a fix, hopefully it will work for you now!

**Closed as completed by d0sboots** 2022-08-26 01:49 UTC
